// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type GetHealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthcheckResponses = {
    /**
     * API is healthy
     */
    200: {
        /**
         * Current API health status.
         */
        status: 'ok';
    };
};

export type GetHealthcheckResponse = GetHealthcheckResponses[keyof GetHealthcheckResponses];

export type ListIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A cursor for pagination, representing the last item from the previous page.
         */
        cursor?: number | null;
        /**
         * Sorting order as a tuple: [field, direction]. Example: ['id', 'desc'].
         */
        sort?: [
            string,
            string
        ] | null;
        /**
         * Number of incidents to return per page (1-100).
         */
        pageSize?: number;
        /**
         * Search query string to filter incidents by text.
         */
        q?: string | null;
        /**
         * Start timestamp (inclusive) for filtering incidents, in ISO 8601 datetime format with timezone.
         */
        start?: string | null;
        /**
         * End timestamp (inclusive) for filtering incidents, in ISO 8601 datetime format with timezone.
         */
        end?: string | null;
        /**
         * List of station IDs to filter incidents.
         */
        stations?: number | null | Array<number | null> | unknown;
        /**
         * List of incident IDs to filter incidents.
         */
        ids?: number | null | Array<number | null> | unknown;
        /**
         * List of incident types to filter incidents.
         */
        types?: string | Array<string>;
        /**
         * Filter by open status. true: only open incidents, false: only closed incidents
         */
        open?: string | null;
        /**
         * Bounding box for filtering incidents by location.
         */
        bounds?: {
            north: number | null;
            south: number | null;
            east: number | null;
            west: number | null;
        } | null;
    };
    url: '/incidents';
};

export type ListIncidentsResponses = {
    /**
     * Response containing a list of incidents and pagination metadata
     */
    200: {
        /**
         * Pagination metadata
         */
        meta: {
            /**
             * Cursor for pagination; null if there is no next page
             */
            cursor: number | null;
            /**
             * Indicates if there is a previous page of results
             */
            hasPreviousPage: boolean;
            /**
             * Indicates if there is a next page of results
             */
            hasNextPage: boolean;
        };
        /**
         * Array of incident list items
         */
        data: Array<{
            /**
             * The ID of the incident.
             */
            id: number;
            /**
             * URL-friendly slug for the incident.
             */
            slug: string;
            /**
             * Human-readable title for the incident.
             */
            title: string;
            /**
             * Whether the incident is currently open.
             */
            isOpen: boolean;
            /**
             * The consecutive number of the incident.
             */
            EEConsecutive: string;
            /**
             * The address of the incident.
             */
            address: string;
            /**
             * The timestamp of the incident.
             */
            incidentTimestamp: string;
            /**
             * The timestamp when the incident was last modified.
             */
            modifiedAt: string;
            /**
             * The important details of the incident.
             */
            importantDetails: string;
            /**
             * The latitude coordinate of the incident.
             */
            latitude: number;
            /**
             * The longitude coordinate of the incident.
             */
            longitude: number;
            /**
             * Whether the incident coordinates are temporary placeholders derived from dispatched stations.
             */
            isTemporaryCoordinates: boolean;
            /**
             * URL to the incident's map image.
             */
            mapImageUrl: string | null;
            /**
             * General type assigned by dispatch.
             */
            dispatchType: {
                /**
                 * Type code.
                 */
                code: string;
                /**
                 * Type name.
                 */
                name: string;
                /**
                 * URL to the type's icon image.
                 */
                imageUrl: string | null;
            } | null;
            /**
             * Specific type assigned by dispatch.
             */
            specificDispatchType: {
                /**
                 * Type code.
                 */
                code: string;
                /**
                 * Type name.
                 */
                name: string;
                /**
                 * URL to the type's icon image.
                 */
                imageUrl: string | null;
            } | null;
            /**
             * Actual general type (set by firefighters on scene).
             */
            actualType: {
                /**
                 * Type code.
                 */
                code: string;
                /**
                 * Type name.
                 */
                name: string;
                /**
                 * URL to the type's icon image.
                 */
                imageUrl: string | null;
            } | null;
            /**
             * Actual specific type (set by firefighters on scene).
             */
            specificActualType: {
                /**
                 * Type code.
                 */
                code: string;
                /**
                 * Type name.
                 */
                name: string;
                /**
                 * URL to the type's icon image.
                 */
                imageUrl: string | null;
            } | null;
            /**
             * Name of the responsible station for the incident.
             */
            responsibleStationName: string | null;
            /**
             * Name of the district where the incident occurred.
             */
            districtName: string | null;
            /**
             * Number of stations dispatched to the incident.
             */
            dispatchedStationsCount: number;
            /**
             * Number of vehicles dispatched to the incident.
             */
            dispatchedVehiclesCount: number;
            /**
             * Total dispatched (stations + vehicles).
             */
            totalDispatched: number;
        }>;
    };
};

export type ListIncidentsResponse = ListIncidentsResponses[keyof ListIncidentsResponses];

export type GetIncidentByIdData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}';
};

export type GetIncidentByIdErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentByIdError = GetIncidentByIdErrors[keyof GetIncidentByIdErrors];

export type GetIncidentByIdResponses = {
    /**
     * Incident object
     */
    200: {
        /**
         * The ID of the incident.
         */
        id: number;
        /**
         * URL-friendly slug for the incident.
         */
        slug: string;
        /**
         * Human-readable title for the incident.
         */
        title: string;
        /**
         * Whether the incident is currently open.
         */
        isOpen: boolean;
        /**
         * The consecutive number of the incident.
         */
        EEConsecutive: string;
        /**
         * The address of the incident.
         */
        address: string;
        /**
         * The timestamp of the incident.
         */
        incidentTimestamp: string;
        /**
         * The timestamp when the incident was last modified.
         */
        modifiedAt: string;
        /**
         * The important details of the incident.
         */
        importantDetails: string;
        /**
         * The latitude coordinate of the incident.
         */
        latitude: number;
        /**
         * The longitude coordinate of the incident.
         */
        longitude: number;
        /**
         * Whether the incident coordinates are temporary placeholders derived from dispatched stations.
         */
        isTemporaryCoordinates: boolean;
        /**
         * Name of the canton where the incident occurred.
         */
        cantonName: string | null;
        /**
         * URL to the incident's map image.
         */
        mapImageUrl: string | null;
        /**
         * General type assigned by dispatch.
         */
        dispatchType: {
            /**
             * Type code.
             */
            code: string;
            /**
             * Type name.
             */
            name: string;
            /**
             * URL to the type's icon image.
             */
            imageUrl: string | null;
        } | null;
        /**
         * Specific type assigned by dispatch.
         */
        specificDispatchType: {
            /**
             * Type code.
             */
            code: string;
            /**
             * Type name.
             */
            name: string;
            /**
             * URL to the type's icon image.
             */
            imageUrl: string | null;
        } | null;
        /**
         * Actual general type (set by firefighters on scene).
         */
        actualType: {
            /**
             * Type code.
             */
            code: string;
            /**
             * Type name.
             */
            name: string;
            /**
             * URL to the type's icon image.
             */
            imageUrl: string | null;
        } | null;
        /**
         * Actual specific type (set by firefighters on scene).
         */
        specificActualType: {
            /**
             * Type code.
             */
            code: string;
            /**
             * Type name.
             */
            name: string;
            /**
             * URL to the type's icon image.
             */
            imageUrl: string | null;
        } | null;
        /**
         * Statistics about incidents of this type.
         */
        statistics: {
            /**
             * The year of the incident.
             */
            currentYear: number;
            /**
             * Count of incidents of this type in the incident's year.
             */
            currentYearCount: number;
            /**
             * Count of incidents of this type in the incident's canton for that year.
             */
            currentYearCantonCount: number;
            /**
             * The year before the incident.
             */
            previousYear: number;
            /**
             * Count of incidents of this type in the previous year.
             */
            previousYearCount: number;
        };
        /**
         * Stations dispatched to the incident.
         */
        dispatchedStations: Array<{
            /**
             * The station name.
             */
            name: string;
            /**
             * The station key.
             */
            stationKey: string;
            /**
             * URL to the station's image.
             */
            imageUrl: string;
            /**
             * Whether the station is responsible for the incident.
             */
            isResponsible: boolean;
            /**
             * Vehicles dispatched from this station.
             */
            vehicles: Array<{
                /**
                 * The vehicle ID.
                 */
                id: number;
                /**
                 * The internal vehicle number.
                 */
                internalNumber: string;
                /**
                 * The vehicle plate number.
                 */
                plate: string;
                /**
                 * The vehicle type.
                 */
                type: string;
                /**
                 * Time when the vehicle was dispatched.
                 */
                dispatchedTime: string;
                /**
                 * Time when the vehicle arrived at the scene.
                 */
                arrivalTime: string | null;
                /**
                 * Time when the vehicle departed from the scene.
                 */
                departureTime: string | null;
                /**
                 * Time when the vehicle returned to base.
                 */
                baseReturnTime: string | null;
            }>;
        }>;
    };
};

export type GetIncidentByIdResponse = GetIncidentByIdResponses[keyof GetIncidentByIdResponses];

export type GetIncidentTimelineData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/timeline';
};

export type GetIncidentTimelineErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentTimelineError = GetIncidentTimelineErrors[keyof GetIncidentTimelineErrors];

export type GetIncidentTimelineResponses = {
    /**
     * Timeline events for the incident
     */
    200: {
        events: Array<{
            id: string;
            date: string;
            title: string;
            description?: string;
        }>;
    };
};

export type GetIncidentTimelineResponse = GetIncidentTimelineResponses[keyof GetIncidentTimelineResponses];

export type GetIncidentResponseTimesData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/response-times';
};

export type GetIncidentResponseTimesErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentResponseTimesError = GetIncidentResponseTimesErrors[keyof GetIncidentResponseTimesErrors];

export type GetIncidentResponseTimesResponses = {
    /**
     * Response time breakdown for dispatched vehicles
     */
    200: {
        /**
         * Array of vehicle response time data.
         */
        vehicles: Array<{
            /**
             * The vehicle dispatch ID.
             */
            id: number;
            /**
             * The vehicle internal number.
             */
            vehicle: string;
            /**
             * The station name.
             */
            station: string;
            /**
             * Time when the vehicle was dispatched.
             */
            dispatchedTime: string | null;
            /**
             * Time when the vehicle arrived at the scene.
             */
            arrivalTime: string | null;
            /**
             * Time when the vehicle departed from the scene.
             */
            departureTime: string | null;
            /**
             * Time when the vehicle returned to base.
             */
            baseReturnTime: string | null;
            /**
             * Time in seconds from dispatch to arrival.
             */
            responseTimeSeconds: number;
            /**
             * Time in seconds the vehicle was on scene.
             */
            onSceneTimeSeconds: number;
            /**
             * Time in seconds from departure to base return.
             */
            returnTimeSeconds: number;
            /**
             * Total time in seconds (response + on scene + return).
             */
            totalTimeSeconds: number;
            /**
             * Whether the vehicle is still en route (departed but not returned).
             */
            isEnRoute: boolean;
        }>;
    };
};

export type GetIncidentResponseTimesResponse = GetIncidentResponseTimesResponses[keyof GetIncidentResponseTimesResponses];

export type GetIncidentOgImageData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/og';
};

export type GetIncidentOgImageErrors = {
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentOgImageError = GetIncidentOgImageErrors[keyof GetIncidentOgImageErrors];

export type GetIncidentOgImageResponses = {
    /**
     * OG Image for the incident
     */
    200: Blob | File;
};

export type GetIncidentOgImageResponse = GetIncidentOgImageResponses[keyof GetIncidentOgImageResponses];

export type GetIncidentMapData = {
    body?: never;
    path: {
        id: number | null;
    };
    query?: never;
    url: '/incidents/{id}/map';
};

export type GetIncidentMapErrors = {
    /**
     * Invalid coordinates
     */
    400: {
        message: string;
    };
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch map image
     */
    502: {
        message: string;
    };
};

export type GetIncidentMapError = GetIncidentMapErrors[keyof GetIncidentMapErrors];

export type GetIncidentMapResponses = {
    /**
     * Map image for the incident
     */
    200: Blob | File;
};

export type GetIncidentMapResponse = GetIncidentMapResponses[keyof GetIncidentMapResponses];

export type GetIncidentOriginalMapData = {
    body?: never;
    path: {
        id: number | null;
    };
    query: {
        /**
         * The admin token.
         */
        token: string;
    };
    url: '/incidents/{id}/map/original';
};

export type GetIncidentOriginalMapErrors = {
    /**
     * Invalid coordinates
     */
    400: {
        message: string;
    };
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * Incident not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch map image
     */
    502: {
        message: string;
    };
};

export type GetIncidentOriginalMapError = GetIncidentOriginalMapErrors[keyof GetIncidentOriginalMapErrors];

export type GetIncidentOriginalMapResponses = {
    /**
     * Original map image from Mapbox (PNG)
     */
    200: Blob | File;
};

export type GetIncidentOriginalMapResponse = GetIncidentOriginalMapResponses[keyof GetIncidentOriginalMapResponses];

export type ListStationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of stations to return per page.
         */
        limit?: number;
        /**
         * Page number for pagination.
         */
        page?: number;
        /**
         * Sorting order as a tuple: [field, direction].
         */
        sort?: [
            string,
            string
        ] | null;
        /**
         * Search by station name or key.
         */
        q?: string;
        /**
         * Filter by operative status.
         */
        operative?: string;
        /**
         * Bounding box for filtering stations by location.
         */
        bounds?: {
            north: number | null;
            south: number | null;
            east: number | null;
            west: number | null;
        } | null;
    };
    url: '/stations';
};

export type ListStationsResponses = {
    /**
     * List of stations
     */
    200: {
        data: Array<{
            /**
             * Station ID.
             */
            id: number;
            /**
             * Station name.
             */
            name: string;
            /**
             * Station key.
             */
            stationKey: string;
            /**
             * Radio channel designation.
             */
            radioChannel: string | null;
            /**
             * Station latitude.
             */
            latitude: string;
            /**
             * Station longitude.
             */
            longitude: string;
            /**
             * Station address.
             */
            address: string | null;
            /**
             * Station phone number.
             */
            phoneNumber: string | null;
            /**
             * Station fax number.
             */
            fax: string | null;
            /**
             * Station email.
             */
            email: string | null;
            /**
             * Whether the station is operative.
             */
            isOperative: boolean | null;
            /**
             * Station image URL.
             */
            imageUrl: string;
        }>;
        meta: {
            /**
             * Current page number.
             */
            page: number;
            /**
             * Items per page.
             */
            limit: number;
            /**
             * Total number of stations.
             */
            total: number;
            /**
             * Total number of pages.
             */
            totalPages: number;
            /**
             * Whether a next page exists.
             */
            hasNextPage: boolean;
            /**
             * Whether a previous page exists.
             */
            hasPreviousPage: boolean;
        };
    };
};

export type ListStationsResponse = ListStationsResponses[keyof ListStationsResponses];

export type GetStationsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stations/overview';
};

export type GetStationsOverviewResponses = {
    /**
     * Stations overview statistics
     */
    200: {
        /**
         * Number of operative stations.
         */
        operativeStationsCount: number;
        /**
         * Number of active vehicles (available or in incident).
         */
        operativeVehiclesCount: number;
        /**
         * Average response time in seconds over the last 30 days (outliers removed).
         */
        averageResponseTimeSeconds: number | null;
    };
};

export type GetStationsOverviewResponse = GetStationsOverviewResponses[keyof GetStationsOverviewResponses];

export type GetStationByNameData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query?: never;
    url: '/stations/{name}';
};

export type GetStationByNameErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationByNameError = GetStationByNameErrors[keyof GetStationByNameErrors];

export type GetStationByNameResponses = {
    /**
     * Station details
     */
    200: {
        station: {
            /**
             * Station ID.
             */
            id: number;
            /**
             * Station name.
             */
            name: string;
            /**
             * Station key.
             */
            stationKey: string;
            /**
             * Radio channel designation.
             */
            radioChannel: string | null;
            /**
             * Station latitude.
             */
            latitude: string;
            /**
             * Station longitude.
             */
            longitude: string;
            /**
             * Station address.
             */
            address: string | null;
            /**
             * Station phone number.
             */
            phoneNumber: string | null;
            /**
             * Station fax number.
             */
            fax: string | null;
            /**
             * Station email.
             */
            email: string | null;
            /**
             * Whether the station is operative.
             */
            isOperative: boolean | null;
            /**
             * Station image URL.
             */
            imageUrl: string;
        };
    };
};

export type GetStationByNameResponse = GetStationByNameResponses[keyof GetStationByNameResponses];

export type GetStationHeatmapData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query?: {
        /**
         * Number of days to include in heatmap data.
         */
        days?: number;
    };
    url: '/stations/{name}/heatmap';
};

export type GetStationHeatmapErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationHeatmapError = GetStationHeatmapErrors[keyof GetStationHeatmapErrors];

export type GetStationHeatmapResponses = {
    /**
     * Incident heatmap data
     */
    200: {
        data: Array<{
            /**
             * Day in YYYY-MM-DD format.
             */
            date: string;
            /**
             * Number of incidents on that day.
             */
            count: number;
        }>;
        /**
         * Total incidents in the requested range.
         */
        totalIncidents: number;
    };
};

export type GetStationHeatmapResponse = GetStationHeatmapResponses[keyof GetStationHeatmapResponses];

export type GetStationHighlightedIncidentsData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query?: {
        /**
         * Time range in days to look for incidents.
         */
        timeRange?: number;
        /**
         * Maximum number of incidents to return.
         */
        limit?: number;
    };
    url: '/stations/{name}/highlighted-incidents';
};

export type GetStationHighlightedIncidentsErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationHighlightedIncidentsError = GetStationHighlightedIncidentsErrors[keyof GetStationHighlightedIncidentsErrors];

export type GetStationHighlightedIncidentsResponses = {
    /**
     * Highlighted incidents for the station
     */
    200: {
        incidents: Array<{
            /**
             * Incident ID.
             */
            id: number;
            /**
             * Incident timestamp.
             */
            incidentTimestamp: string;
            /**
             * Incident details.
             */
            details: string | null;
            /**
             * Incident address.
             */
            address: string | null;
            /**
             * Responsible station name.
             */
            responsibleStation: string | null;
            /**
             * Incident latitude.
             */
            latitude: string;
            /**
             * Incident longitude.
             */
            longitude: string;
            /**
             * URL to the incident's map image.
             */
            mapImageUrl: string | null;
            /**
             * Number of dispatched vehicles.
             */
            dispatchedVehiclesCount: number;
            /**
             * Number of dispatched stations.
             */
            dispatchedStationsCount: number;
        }>;
    };
};

export type GetStationHighlightedIncidentsResponse = GetStationHighlightedIncidentsResponses[keyof GetStationHighlightedIncidentsResponses];

export type GetStationCollaborationsData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query?: never;
    url: '/stations/{name}/collaborations';
};

export type GetStationCollaborationsErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationCollaborationsError = GetStationCollaborationsErrors[keyof GetStationCollaborationsErrors];

export type GetStationCollaborationsResponses = {
    /**
     * Stations that collaborated with this one
     */
    200: {
        collaborations: Array<{
            /**
             * Station ID.
             */
            id: number;
            /**
             * Station name.
             */
            name: string;
            /**
             * Station key.
             */
            stationKey: string;
            /**
             * Station image URL.
             */
            imageUrl: string;
            /**
             * Number of collaborations with the station.
             */
            collaborationCount: number;
        }>;
    };
};

export type GetStationCollaborationsResponse = GetStationCollaborationsResponses[keyof GetStationCollaborationsResponses];

export type GetStationVehiclesData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query?: never;
    url: '/stations/{name}/vehicles';
};

export type GetStationVehiclesErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
};

export type GetStationVehiclesError = GetStationVehiclesErrors[keyof GetStationVehiclesErrors];

export type GetStationVehiclesResponses = {
    /**
     * Vehicles assigned to this station with stats
     */
    200: {
        vehicles: Array<{
            /**
             * Vehicle ID.
             */
            id: number;
            /**
             * Vehicle internal number.
             */
            internalNumber: string | null;
            /**
             * Vehicle plate number.
             */
            plate: string | null;
            /**
             * Vehicle type description.
             */
            descriptionType: string | null;
            /**
             * Vehicle class.
             */
            class: string | null;
            /**
             * Operational status description.
             */
            descriptionOperationalStatus: string | null;
            stats: {
                /**
                 * Number of incidents the vehicle was dispatched to.
                 */
                incidentCount: number;
                /**
                 * Average response time in seconds.
                 */
                avgResponseTimeSeconds: number | null;
            };
        }>;
    };
};

export type GetStationVehiclesResponse = GetStationVehiclesResponses[keyof GetStationVehiclesResponses];

export type GetStationImageData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query?: never;
    url: '/stations/{name}/image';
};

export type GetStationImageErrors = {
    /**
     * Station not found
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch station image
     */
    502: {
        message: string;
    };
};

export type GetStationImageError = GetStationImageErrors[keyof GetStationImageErrors];

export type GetStationImageResponses = {
    /**
     * Station image
     */
    200: Blob | File;
};

export type GetStationImageResponse = GetStationImageResponses[keyof GetStationImageResponses];

export type GetStationOriginalImageData = {
    body?: never;
    path: {
        /**
         * Station name.
         */
        name: string;
    };
    query: {
        /**
         * Token required to access the original image.
         */
        token: string;
    };
    url: '/stations/{name}/image/original';
};

export type GetStationOriginalImageErrors = {
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * Station image not found
     */
    404: {
        message: string;
    };
};

export type GetStationOriginalImageError = GetStationOriginalImageErrors[keyof GetStationOriginalImageErrors];

export type GetStationOriginalImageResponses = {
    /**
     * Original station image
     */
    200: Blob | File;
};

export type GetStationOriginalImageResponse = GetStationOriginalImageResponses[keyof GetStationOriginalImageResponses];

export type GetYearRecapData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Year to get recap for.
         */
        year?: number;
    };
    url: '/stats/year-recap';
};

export type GetYearRecapResponses = {
    /**
     * Year-to-date statistics about emergency response
     */
    200: {
        /**
         * Top 5 days with the most incidents in the selected year.
         */
        topIncidentDays: Array<{
            /**
             * Date in YYYY-MM-DD format.
             */
            date: string;
            /**
             * Number of incidents on that date.
             */
            count: number;
        }>;
        /**
         * Top 5 stations with the most dispatches in the selected year.
         */
        topDispatchedStations: Array<{
            /**
             * Station name.
             */
            name: string;
            /**
             * Number of dispatches.
             */
            count: number;
        }>;
        /**
         * Top 5 vehicles with the most dispatches in the selected year.
         */
        topDispatchedVehicles: Array<{
            /**
             * Vehicle internal number.
             */
            internalNumber: string;
            /**
             * Station name assigned to the vehicle.
             */
            stationName: string;
            /**
             * Number of dispatches.
             */
            count: number;
        }>;
    };
};

export type GetYearRecapResponse = GetYearRecapResponses[keyof GetYearRecapResponses];

export type GetIncidentsByTypeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start timestamp (inclusive) for filtering, in ISO 8601 datetime format with timezone.
         */
        start?: string | null;
        /**
         * End timestamp (inclusive) for filtering, in ISO 8601 datetime format with timezone.
         */
        end?: string | null;
        /**
         * Maximum number of incident types to return before grouping the rest as 'Otros'.
         */
        limit?: number;
    };
    url: '/stats/incidents-by-type';
};

export type GetIncidentsByTypeResponses = {
    /**
     * Incidents grouped by type, including top N types and an optional 'Otros' bucket for the rest
     */
    200: Array<{
        /**
         * Incident type code used for filtering. Null when the bucket cannot be filtered directly.
         */
        code: string | null;
        /**
         * Incident type name.
         */
        name: string;
        /**
         * Number of incidents for this type.
         */
        count: number;
    }>;
};

export type GetIncidentsByTypeResponse = GetIncidentsByTypeResponses[keyof GetIncidentsByTypeResponses];

export type GetDailyResponseTimesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Time range in days. Allowed values: 7, 30, 90, 365.
         */
        timeRange?: number;
    };
    url: '/stats/daily-response-times';
};

export type GetDailyResponseTimesResponses = {
    /**
     * Daily average response times for dispatched vehicles
     */
    200: {
        data: Array<{
            /**
             * Day in YYYY-MM-DD format.
             */
            date: string;
            /**
             * Average response time in seconds for that day.
             */
            averageResponseTimeSeconds: number;
            /**
             * Number of dispatched vehicles considered for that day.
             */
            dispatchCount: number;
        }>;
        /**
         * Total dispatched vehicles considered in the requested range.
         */
        totalDispatches: number;
    };
};

export type GetDailyResponseTimesResponse = GetDailyResponseTimesResponses[keyof GetDailyResponseTimesResponses];

export type GetIncidentsByHourData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Time range in hours. Allowed values: 24, 48, 72.
         */
        timeRange?: number;
    };
    url: '/stats/incidents-by-hour';
};

export type GetIncidentsByHourResponses = {
    /**
     * Hourly incident counts for the requested 24, 48, or 72 hour range
     */
    200: {
        data: Array<{
            /**
             * Hour bucket start timestamp in ISO 8601 format.
             */
            hourStart: string;
            /**
             * Localized hour label in Costa Rica time.
             */
            hourLabel: string;
            /**
             * How many hours ago this bucket starts from the current hour.
             */
            hoursAgo: number;
            /**
             * Number of incidents in that hour bucket.
             */
            incidents: number;
        }>;
        /**
         * Total incidents in the requested hourly range.
         */
        totalIncidents: number;
    };
};

export type GetIncidentsByHourResponse = GetIncidentsByHourResponses[keyof GetIncidentsByHourResponses];

export type GetSystemOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/system-overview';
};

export type GetSystemOverviewResponses = {
    /**
     * System overview statistics
     */
    200: {
        /**
         * Number of operative stations.
         */
        stationCount: number;
        /**
         * Number of active vehicles.
         */
        activeVehicleCount: number;
        /**
         * Average response time in minutes over last 30 days.
         */
        avgResponseTimeMinutes: number | null;
    };
};

export type GetSystemOverviewResponse = GetSystemOverviewResponses[keyof GetSystemOverviewResponses];

export type ListIncidentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/types';
};

export type ListIncidentTypesResponses = {
    /**
     * List of incident types
     */
    200: {
        /**
         * Flat list of incident types
         */
        items: Array<{
            /**
             * Incident type code
             */
            code: string;
            /**
             * Incident type name
             */
            name: string;
            /**
             * URL to the incident type image
             */
            imageUrl: string;
            /**
             * Parent incident type code
             */
            parentCode: string | null;
            /**
             * Depth level based on code segments
             */
            level: number;
        }>;
    };
};

export type ListIncidentTypesResponse = ListIncidentTypesResponses[keyof ListIncidentTypesResponses];

export type GetIncidentTypeData = {
    body?: never;
    path: {
        /**
         * Incident type code (e.g., '1' for fire, '6.1.1.2.1' for snake rescue)
         */
        code: string;
    };
    query?: {
        /**
         * Comma-separated includes: children, ancestors
         */
        include?: string;
    };
    url: '/types/{code}';
};

export type GetIncidentTypeErrors = {
    /**
     * Incident type not found
     */
    404: {
        message: string;
    };
};

export type GetIncidentTypeError = GetIncidentTypeErrors[keyof GetIncidentTypeErrors];

export type GetIncidentTypeResponses = {
    /**
     * Incident type details
     */
    200: {
        type: {
            /**
             * Incident type code
             */
            code: string;
            /**
             * Incident type name
             */
            name: string;
            /**
             * URL to the incident type image
             */
            imageUrl: string;
            /**
             * Parent incident type code
             */
            parentCode: string | null;
            /**
             * Depth level based on code segments
             */
            level: number;
        };
        /**
         * Direct children of this incident type
         */
        children?: Array<{
            /**
             * Child incident type code
             */
            code: string;
            /**
             * Child incident type name
             */
            name: string;
            /**
             * URL to the incident type image
             */
            imageUrl: string;
        }>;
        /**
         * Ancestors of this incident type
         */
        ancestors?: Array<{
            /**
             * Ancestor incident type code
             */
            code: string;
            /**
             * Ancestor incident type name
             */
            name: string;
            /**
             * URL to the incident type image
             */
            imageUrl: string;
            /**
             * Depth level based on code segments
             */
            level: number;
        }>;
    };
};

export type GetIncidentTypeResponse = GetIncidentTypeResponses[keyof GetIncidentTypeResponses];

export type GetIncidentTypeImageData = {
    body?: never;
    path: {
        /**
         * Incident type code (e.g., '1' for fire, '6.1.1.2.1' for snake rescue)
         */
        code: string;
    };
    query?: never;
    url: '/types/{code}/image';
};

export type GetIncidentTypeImageErrors = {
    /**
     * No image found for this incident type or its parents
     */
    404: {
        message: string;
    };
    /**
     * Failed to fetch image from image proxy
     */
    502: {
        message: string;
    };
};

export type GetIncidentTypeImageError = GetIncidentTypeImageErrors[keyof GetIncidentTypeImageErrors];

export type GetIncidentTypeImageResponses = {
    /**
     * Incident type illustration image
     */
    200: Blob | File;
};

export type GetIncidentTypeImageResponse = GetIncidentTypeImageResponses[keyof GetIncidentTypeImageResponses];

export type GetIncidentTypeOriginalImageData = {
    body?: never;
    path: {
        /**
         * Incident type code (e.g., '1' for fire, '6.1.1.2.1' for snake rescue)
         */
        code: string;
    };
    query: {
        /**
         * The admin token.
         */
        token: string;
    };
    url: '/types/{code}/image/original';
};

export type GetIncidentTypeOriginalImageErrors = {
    /**
     * Invalid or missing token
     */
    401: {
        message: string;
    };
    /**
     * No image found for this incident type or its parents
     */
    404: {
        message: string;
    };
};

export type GetIncidentTypeOriginalImageError = GetIncidentTypeOriginalImageErrors[keyof GetIncidentTypeOriginalImageErrors];

export type GetIncidentTypeOriginalImageResponses = {
    /**
     * Original incident type image (PNG)
     */
    200: Blob | File;
};

export type GetIncidentTypeOriginalImageResponse = GetIncidentTypeOriginalImageResponses[keyof GetIncidentTypeOriginalImageResponses];
