/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStationsDotxmlRouteImport } from './routes/sitemap-stations[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapIncidentsDotxmlRouteImport } from './routes/sitemap-incidents[.]xml'
import { Route as SitemapIncidentsChar123yearMonthChar125DotxmlRouteImport } from './routes/sitemap-incidents-{$yearMonth}[.]xml'
import { Route as IncidentsRouteImport } from './routes/_incidents'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as IncidentsIncidentesIndexRouteImport } from './routes/_incidents/incidentes/index'
import { Route as DashboardEstacionesIndexRouteImport } from './routes/_dashboard/estaciones/index'
import { Route as DashboardIncidentesSlugRouteImport } from './routes/_dashboard/incidentes/$slug'
import { Route as DashboardEstacionesNameRouteImport } from './routes/_dashboard/estaciones/$name'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStationsDotxmlRoute = SitemapStationsDotxmlRouteImport.update({
  id: '/sitemap-stations.xml',
  path: '/sitemap-stations.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIncidentsDotxmlRoute = SitemapIncidentsDotxmlRouteImport.update({
  id: '/sitemap-incidents.xml',
  path: '/sitemap-incidents.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIncidentsChar123yearMonthChar125DotxmlRoute =
  SitemapIncidentsChar123yearMonthChar125DotxmlRouteImport.update({
    id: '/sitemap-incidents-{$yearMonth}.xml',
    path: '/sitemap-incidents-{$yearMonth}.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/_incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const IncidentsIncidentesIndexRoute =
  IncidentsIncidentesIndexRouteImport.update({
    id: '/incidentes/',
    path: '/incidentes/',
    getParentRoute: () => IncidentsRoute,
  } as any)
const DashboardEstacionesIndexRoute =
  DashboardEstacionesIndexRouteImport.update({
    id: '/estaciones/',
    path: '/estaciones/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIncidentesSlugRoute = DashboardIncidentesSlugRouteImport.update({
  id: '/incidentes/$slug',
  path: '/incidentes/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstacionesNameRoute = DashboardEstacionesNameRouteImport.update({
  id: '/estaciones/$name',
  path: '/estaciones/$name',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/sitemap-incidents-{$yearMonth}.xml': typeof SitemapIncidentsChar123yearMonthChar125DotxmlRoute
  '/sitemap-incidents.xml': typeof SitemapIncidentsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-stations.xml': typeof SitemapStationsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/estaciones/$name': typeof DashboardEstacionesNameRoute
  '/incidentes/$slug': typeof DashboardIncidentesSlugRoute
  '/estaciones/': typeof DashboardEstacionesIndexRoute
  '/incidentes/': typeof IncidentsIncidentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/sitemap-incidents-{$yearMonth}.xml': typeof SitemapIncidentsChar123yearMonthChar125DotxmlRoute
  '/sitemap-incidents.xml': typeof SitemapIncidentsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-stations.xml': typeof SitemapStationsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/estaciones/$name': typeof DashboardEstacionesNameRoute
  '/incidentes/$slug': typeof DashboardIncidentesSlugRoute
  '/estaciones': typeof DashboardEstacionesIndexRoute
  '/incidentes': typeof IncidentsIncidentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_incidents': typeof IncidentsRouteWithChildren
  '/sitemap-incidents-{$yearMonth}.xml': typeof SitemapIncidentsChar123yearMonthChar125DotxmlRoute
  '/sitemap-incidents.xml': typeof SitemapIncidentsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-stations.xml': typeof SitemapStationsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/estaciones/$name': typeof DashboardEstacionesNameRoute
  '/_dashboard/incidentes/$slug': typeof DashboardIncidentesSlugRoute
  '/_dashboard/estaciones/': typeof DashboardEstacionesIndexRoute
  '/_incidents/incidentes/': typeof IncidentsIncidentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap-incidents-{$yearMonth}.xml'
    | '/sitemap-incidents.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-stations.xml'
    | '/sitemap.xml'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones/'
    | '/incidentes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap-incidents-{$yearMonth}.xml'
    | '/sitemap-incidents.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-stations.xml'
    | '/sitemap.xml'
    | '/estaciones/$name'
    | '/incidentes/$slug'
    | '/estaciones'
    | '/incidentes'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_incidents'
    | '/sitemap-incidents-{$yearMonth}.xml'
    | '/sitemap-incidents.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-stations.xml'
    | '/sitemap.xml'
    | '/_dashboard/'
    | '/_dashboard/estaciones/$name'
    | '/_dashboard/incidentes/$slug'
    | '/_dashboard/estaciones/'
    | '/_incidents/incidentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  IncidentsRoute: typeof IncidentsRouteWithChildren
  SitemapIncidentsChar123yearMonthChar125DotxmlRoute: typeof SitemapIncidentsChar123yearMonthChar125DotxmlRoute
  SitemapIncidentsDotxmlRoute: typeof SitemapIncidentsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapStationsDotxmlRoute: typeof SitemapStationsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-stations.xml': {
      id: '/sitemap-stations.xml'
      path: '/sitemap-stations.xml'
      fullPath: '/sitemap-stations.xml'
      preLoaderRoute: typeof SitemapStationsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-incidents.xml': {
      id: '/sitemap-incidents.xml'
      path: '/sitemap-incidents.xml'
      fullPath: '/sitemap-incidents.xml'
      preLoaderRoute: typeof SitemapIncidentsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-incidents-{$yearMonth}.xml': {
      id: '/sitemap-incidents-{$yearMonth}.xml'
      path: '/sitemap-incidents-{$yearMonth}.xml'
      fullPath: '/sitemap-incidents-{$yearMonth}.xml'
      preLoaderRoute: typeof SitemapIncidentsChar123yearMonthChar125DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_incidents': {
      id: '/_incidents'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_incidents/incidentes/': {
      id: '/_incidents/incidentes/'
      path: '/incidentes'
      fullPath: '/incidentes/'
      preLoaderRoute: typeof IncidentsIncidentesIndexRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/_dashboard/estaciones/': {
      id: '/_dashboard/estaciones/'
      path: '/estaciones'
      fullPath: '/estaciones/'
      preLoaderRoute: typeof DashboardEstacionesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/incidentes/$slug': {
      id: '/_dashboard/incidentes/$slug'
      path: '/incidentes/$slug'
      fullPath: '/incidentes/$slug'
      preLoaderRoute: typeof DashboardIncidentesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/estaciones/$name': {
      id: '/_dashboard/estaciones/$name'
      path: '/estaciones/$name'
      fullPath: '/estaciones/$name'
      preLoaderRoute: typeof DashboardEstacionesNameRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEstacionesNameRoute: typeof DashboardEstacionesNameRoute
  DashboardIncidentesSlugRoute: typeof DashboardIncidentesSlugRoute
  DashboardEstacionesIndexRoute: typeof DashboardEstacionesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEstacionesNameRoute: DashboardEstacionesNameRoute,
  DashboardIncidentesSlugRoute: DashboardIncidentesSlugRoute,
  DashboardEstacionesIndexRoute: DashboardEstacionesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface IncidentsRouteChildren {
  IncidentsIncidentesIndexRoute: typeof IncidentsIncidentesIndexRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentesIndexRoute: IncidentsIncidentesIndexRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  IncidentsRoute: IncidentsRouteWithChildren,
  SitemapIncidentsChar123yearMonthChar125DotxmlRoute:
    SitemapIncidentsChar123yearMonthChar125DotxmlRoute,
  SitemapIncidentsDotxmlRoute: SitemapIncidentsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapStationsDotxmlRoute: SitemapStationsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
