// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getDailyResponseTimes, getHealthcheck, getIncidentById, getIncidentMap, getIncidentOgImage, getIncidentOriginalMap, getIncidentResponseTimes, getIncidentsByHour, getIncidentsByType, getIncidentTimeline, getIncidentType, getIncidentTypeImage, getIncidentTypeOriginalImage, getStationByName, getStationCollaborations, getStationHeatmap, getStationHighlightedIncidents, getStationImage, getStationOriginalImage, getStationsOverview, getStationVehicles, getSystemOverview, getYearRecap, listIncidents, listIncidentTypes, listStations, type Options } from '../sdk.gen';
import type { GetDailyResponseTimesData, GetDailyResponseTimesResponse, GetHealthcheckData, GetHealthcheckResponse, GetIncidentByIdData, GetIncidentByIdError, GetIncidentByIdResponse, GetIncidentMapData, GetIncidentMapError, GetIncidentMapResponse, GetIncidentOgImageData, GetIncidentOgImageError, GetIncidentOgImageResponse, GetIncidentOriginalMapData, GetIncidentOriginalMapError, GetIncidentOriginalMapResponse, GetIncidentResponseTimesData, GetIncidentResponseTimesError, GetIncidentResponseTimesResponse, GetIncidentsByHourData, GetIncidentsByHourResponse, GetIncidentsByTypeData, GetIncidentsByTypeResponse, GetIncidentTimelineData, GetIncidentTimelineError, GetIncidentTimelineResponse, GetIncidentTypeData, GetIncidentTypeError, GetIncidentTypeImageData, GetIncidentTypeImageError, GetIncidentTypeImageResponse, GetIncidentTypeOriginalImageData, GetIncidentTypeOriginalImageError, GetIncidentTypeOriginalImageResponse, GetIncidentTypeResponse, GetStationByNameData, GetStationByNameError, GetStationByNameResponse, GetStationCollaborationsData, GetStationCollaborationsError, GetStationCollaborationsResponse, GetStationHeatmapData, GetStationHeatmapError, GetStationHeatmapResponse, GetStationHighlightedIncidentsData, GetStationHighlightedIncidentsError, GetStationHighlightedIncidentsResponse, GetStationImageData, GetStationImageError, GetStationImageResponse, GetStationOriginalImageData, GetStationOriginalImageError, GetStationOriginalImageResponse, GetStationsOverviewData, GetStationsOverviewResponse, GetStationVehiclesData, GetStationVehiclesError, GetStationVehiclesResponse, GetSystemOverviewData, GetSystemOverviewResponse, GetYearRecapData, GetYearRecapResponse, ListIncidentsData, ListIncidentsResponse, ListIncidentTypesData, ListIncidentTypesResponse, ListStationsData, ListStationsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthcheckQueryKey = (options?: Options<GetHealthcheckData>) => createQueryKey('getHealthcheck', options);

/**
 * Health check
 *
 * Check whether the API is up and responsive
 */
export const getHealthcheckOptions = (options?: Options<GetHealthcheckData>) => queryOptions<GetHealthcheckResponse, DefaultError, GetHealthcheckResponse, ReturnType<typeof getHealthcheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealthcheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthcheckQueryKey(options)
});

export const listIncidentsQueryKey = (options?: Options<ListIncidentsData>) => createQueryKey('listIncidents', options);

/**
 * List all incidents
 *
 * Retrieve a list of incidents
 */
export const listIncidentsOptions = (options?: Options<ListIncidentsData>) => queryOptions<ListIncidentsResponse, DefaultError, ListIncidentsResponse, ReturnType<typeof listIncidentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listIncidents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listIncidentsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listIncidentsInfiniteQueryKey = (options?: Options<ListIncidentsData>): QueryKey<Options<ListIncidentsData>> => createQueryKey('listIncidents', options, true);

/**
 * List all incidents
 *
 * Retrieve a list of incidents
 */
export const listIncidentsInfiniteOptions = (options?: Options<ListIncidentsData>) => infiniteQueryOptions<ListIncidentsResponse, DefaultError, InfiniteData<ListIncidentsResponse>, QueryKey<Options<ListIncidentsData>>, number | null | Pick<QueryKey<Options<ListIncidentsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListIncidentsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                cursor: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listIncidents({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listIncidentsInfiniteQueryKey(options)
});

export const getIncidentByIdQueryKey = (options: Options<GetIncidentByIdData>) => createQueryKey('getIncidentById', options);

/**
 * Retrieve an incident
 *
 * Retrieve an incident by its unique identifier
 */
export const getIncidentByIdOptions = (options: Options<GetIncidentByIdData>) => queryOptions<GetIncidentByIdResponse, GetIncidentByIdError, GetIncidentByIdResponse, ReturnType<typeof getIncidentByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentByIdQueryKey(options)
});

export const getIncidentTimelineQueryKey = (options: Options<GetIncidentTimelineData>) => createQueryKey('getIncidentTimeline', options);

/**
 * Retrieve incident timeline
 *
 * Retrieve timeline events for an incident
 */
export const getIncidentTimelineOptions = (options: Options<GetIncidentTimelineData>) => queryOptions<GetIncidentTimelineResponse, GetIncidentTimelineError, GetIncidentTimelineResponse, ReturnType<typeof getIncidentTimelineQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentTimeline({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentTimelineQueryKey(options)
});

export const getIncidentResponseTimesQueryKey = (options: Options<GetIncidentResponseTimesData>) => createQueryKey('getIncidentResponseTimes', options);

/**
 * Retrieve incident response times
 *
 * Retrieve response time breakdown for dispatched vehicles
 */
export const getIncidentResponseTimesOptions = (options: Options<GetIncidentResponseTimesData>) => queryOptions<GetIncidentResponseTimesResponse, GetIncidentResponseTimesError, GetIncidentResponseTimesResponse, ReturnType<typeof getIncidentResponseTimesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentResponseTimes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentResponseTimesQueryKey(options)
});

export const getIncidentOgImageQueryKey = (options: Options<GetIncidentOgImageData>) => createQueryKey('getIncidentOgImage', options);

/**
 * Retrieve incident Open Graph image
 *
 * Generate the Open Graph image for an incident
 */
export const getIncidentOgImageOptions = (options: Options<GetIncidentOgImageData>) => queryOptions<GetIncidentOgImageResponse, GetIncidentOgImageError, GetIncidentOgImageResponse, ReturnType<typeof getIncidentOgImageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentOgImage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentOgImageQueryKey(options)
});

export const getIncidentMapQueryKey = (options: Options<GetIncidentMapData>) => createQueryKey('getIncidentMap', options);

/**
 * Retrieve incident map image
 *
 * Retrieve the generated map image for an incident
 */
export const getIncidentMapOptions = (options: Options<GetIncidentMapData>) => queryOptions<GetIncidentMapResponse, GetIncidentMapError, GetIncidentMapResponse, ReturnType<typeof getIncidentMapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentMap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentMapQueryKey(options)
});

export const getIncidentOriginalMapQueryKey = (options: Options<GetIncidentOriginalMapData>) => createQueryKey('getIncidentOriginalMap', options);

/**
 * Retrieve original incident map image
 *
 * Retrieve the original map image for an incident from Mapbox
 */
export const getIncidentOriginalMapOptions = (options: Options<GetIncidentOriginalMapData>) => queryOptions<GetIncidentOriginalMapResponse, GetIncidentOriginalMapError, GetIncidentOriginalMapResponse, ReturnType<typeof getIncidentOriginalMapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentOriginalMap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentOriginalMapQueryKey(options)
});

export const listStationsQueryKey = (options?: Options<ListStationsData>) => createQueryKey('listStations', options);

/**
 * List stations
 *
 * Retrieve stations
 */
export const listStationsOptions = (options?: Options<ListStationsData>) => queryOptions<ListStationsResponse, DefaultError, ListStationsResponse, ReturnType<typeof listStationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listStations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listStationsQueryKey(options)
});

export const listStationsInfiniteQueryKey = (options?: Options<ListStationsData>): QueryKey<Options<ListStationsData>> => createQueryKey('listStations', options, true);

/**
 * List stations
 *
 * Retrieve stations
 */
export const listStationsInfiniteOptions = (options?: Options<ListStationsData>) => infiniteQueryOptions<ListStationsResponse, DefaultError, InfiniteData<ListStationsResponse>, QueryKey<Options<ListStationsData>>, number | Pick<QueryKey<Options<ListStationsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListStationsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listStations({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listStationsInfiniteQueryKey(options)
});

export const getStationsOverviewQueryKey = (options?: Options<GetStationsOverviewData>) => createQueryKey('getStationsOverview', options);

/**
 * Get stations overview
 *
 * Get overview statistics for all stations including operative station count, active vehicle count, and average response time
 */
export const getStationsOverviewOptions = (options?: Options<GetStationsOverviewData>) => queryOptions<GetStationsOverviewResponse, DefaultError, GetStationsOverviewResponse, ReturnType<typeof getStationsOverviewQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationsOverview({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationsOverviewQueryKey(options)
});

export const getStationByNameQueryKey = (options: Options<GetStationByNameData>) => createQueryKey('getStationByName', options);

/**
 * Retrieve station
 *
 * Retrieve a station by its name
 */
export const getStationByNameOptions = (options: Options<GetStationByNameData>) => queryOptions<GetStationByNameResponse, GetStationByNameError, GetStationByNameResponse, ReturnType<typeof getStationByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationByNameQueryKey(options)
});

export const getStationHeatmapQueryKey = (options: Options<GetStationHeatmapData>) => createQueryKey('getStationHeatmap', options);

/**
 * Retrieve station heatmap
 *
 * Retrieve incident counts per day for the station
 */
export const getStationHeatmapOptions = (options: Options<GetStationHeatmapData>) => queryOptions<GetStationHeatmapResponse, GetStationHeatmapError, GetStationHeatmapResponse, ReturnType<typeof getStationHeatmapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationHeatmap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationHeatmapQueryKey(options)
});

export const getStationHighlightedIncidentsQueryKey = (options: Options<GetStationHighlightedIncidentsData>) => createQueryKey('getStationHighlightedIncidents', options);

/**
 * Retrieve station highlighted incidents
 *
 * Retrieve highlighted incidents for the station
 */
export const getStationHighlightedIncidentsOptions = (options: Options<GetStationHighlightedIncidentsData>) => queryOptions<GetStationHighlightedIncidentsResponse, GetStationHighlightedIncidentsError, GetStationHighlightedIncidentsResponse, ReturnType<typeof getStationHighlightedIncidentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationHighlightedIncidents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationHighlightedIncidentsQueryKey(options)
});

export const getStationCollaborationsQueryKey = (options: Options<GetStationCollaborationsData>) => createQueryKey('getStationCollaborations', options);

/**
 * Retrieve station collaborations
 *
 * Retrieve stations that collaborated with the given station
 */
export const getStationCollaborationsOptions = (options: Options<GetStationCollaborationsData>) => queryOptions<GetStationCollaborationsResponse, GetStationCollaborationsError, GetStationCollaborationsResponse, ReturnType<typeof getStationCollaborationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationCollaborations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationCollaborationsQueryKey(options)
});

export const getStationVehiclesQueryKey = (options: Options<GetStationVehiclesData>) => createQueryKey('getStationVehicles', options);

/**
 * Retrieve station vehicles
 *
 * Retrieve vehicles assigned to the station with stats
 */
export const getStationVehiclesOptions = (options: Options<GetStationVehiclesData>) => queryOptions<GetStationVehiclesResponse, GetStationVehiclesError, GetStationVehiclesResponse, ReturnType<typeof getStationVehiclesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationVehicles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationVehiclesQueryKey(options)
});

export const getStationImageQueryKey = (options: Options<GetStationImageData>) => createQueryKey('getStationImage', options);

/**
 * Retrieve station image
 *
 * Retrieve the station image. Returns processed image from S3 if available, otherwise returns a generated avatar.
 */
export const getStationImageOptions = (options: Options<GetStationImageData>) => queryOptions<GetStationImageResponse, GetStationImageError, GetStationImageResponse, ReturnType<typeof getStationImageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationImage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationImageQueryKey(options)
});

export const getStationOriginalImageQueryKey = (options: Options<GetStationOriginalImageData>) => createQueryKey('getStationOriginalImage', options);

/**
 * Retrieve original station image
 *
 * Retrieve the original station image from storage
 */
export const getStationOriginalImageOptions = (options: Options<GetStationOriginalImageData>) => queryOptions<GetStationOriginalImageResponse, GetStationOriginalImageError, GetStationOriginalImageResponse, ReturnType<typeof getStationOriginalImageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStationOriginalImage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStationOriginalImageQueryKey(options)
});

export const getYearRecapQueryKey = (options?: Options<GetYearRecapData>) => createQueryKey('getYearRecap', options);

/**
 * Get year recap statistics
 *
 * Year-to-date statistics about emergency response
 */
export const getYearRecapOptions = (options?: Options<GetYearRecapData>) => queryOptions<GetYearRecapResponse, DefaultError, GetYearRecapResponse, ReturnType<typeof getYearRecapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getYearRecap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getYearRecapQueryKey(options)
});

export const getIncidentsByTypeQueryKey = (options?: Options<GetIncidentsByTypeData>) => createQueryKey('getIncidentsByType', options);

/**
 * Get incidents by type
 *
 * Incidents distribution by type with top N and 'Otros' grouping
 */
export const getIncidentsByTypeOptions = (options?: Options<GetIncidentsByTypeData>) => queryOptions<GetIncidentsByTypeResponse, DefaultError, GetIncidentsByTypeResponse, ReturnType<typeof getIncidentsByTypeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByType({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByTypeQueryKey(options)
});

export const getIncidentsByTypeInfiniteQueryKey = (options?: Options<GetIncidentsByTypeData>): QueryKey<Options<GetIncidentsByTypeData>> => createQueryKey('getIncidentsByType', options, true);

/**
 * Get incidents by type
 *
 * Incidents distribution by type with top N and 'Otros' grouping
 */
export const getIncidentsByTypeInfiniteOptions = (options?: Options<GetIncidentsByTypeData>) => infiniteQueryOptions<GetIncidentsByTypeResponse, DefaultError, InfiniteData<GetIncidentsByTypeResponse>, QueryKey<Options<GetIncidentsByTypeData>>, string | null | Pick<QueryKey<Options<GetIncidentsByTypeData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetIncidentsByTypeData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                start: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getIncidentsByType({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByTypeInfiniteQueryKey(options)
});

export const getDailyResponseTimesQueryKey = (options?: Options<GetDailyResponseTimesData>) => createQueryKey('getDailyResponseTimes', options);

/**
 * Get daily response times
 *
 * Daily average response times for dispatched vehicles
 */
export const getDailyResponseTimesOptions = (options?: Options<GetDailyResponseTimesData>) => queryOptions<GetDailyResponseTimesResponse, DefaultError, GetDailyResponseTimesResponse, ReturnType<typeof getDailyResponseTimesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDailyResponseTimes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDailyResponseTimesQueryKey(options)
});

export const getIncidentsByHourQueryKey = (options?: Options<GetIncidentsByHourData>) => createQueryKey('getIncidentsByHour', options);

/**
 * Get incidents by hour
 *
 * Hourly incident counts for the last 24, 48, or 72 hours
 */
export const getIncidentsByHourOptions = (options?: Options<GetIncidentsByHourData>) => queryOptions<GetIncidentsByHourResponse, DefaultError, GetIncidentsByHourResponse, ReturnType<typeof getIncidentsByHourQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentsByHour({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentsByHourQueryKey(options)
});

export const getSystemOverviewQueryKey = (options?: Options<GetSystemOverviewData>) => createQueryKey('getSystemOverview', options);

/**
 * Get system overview
 *
 * System-wide overview statistics including operative stations, active vehicles, and average response time over the last 30 days
 */
export const getSystemOverviewOptions = (options?: Options<GetSystemOverviewData>) => queryOptions<GetSystemOverviewResponse, DefaultError, GetSystemOverviewResponse, ReturnType<typeof getSystemOverviewQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemOverview({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemOverviewQueryKey(options)
});

export const listIncidentTypesQueryKey = (options?: Options<ListIncidentTypesData>) => createQueryKey('listIncidentTypes', options);

/**
 * List incident types
 *
 * Retrieve all incident types with hierarchy metadata
 */
export const listIncidentTypesOptions = (options?: Options<ListIncidentTypesData>) => queryOptions<ListIncidentTypesResponse, DefaultError, ListIncidentTypesResponse, ReturnType<typeof listIncidentTypesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listIncidentTypes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listIncidentTypesQueryKey(options)
});

export const getIncidentTypeQueryKey = (options: Options<GetIncidentTypeData>) => createQueryKey('getIncidentType', options);

/**
 * Retrieve incident type
 *
 * Retrieve a single incident type and its direct children
 */
export const getIncidentTypeOptions = (options: Options<GetIncidentTypeData>) => queryOptions<GetIncidentTypeResponse, GetIncidentTypeError, GetIncidentTypeResponse, ReturnType<typeof getIncidentTypeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentType({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentTypeQueryKey(options)
});

export const getIncidentTypeImageQueryKey = (options: Options<GetIncidentTypeImageData>) => createQueryKey('getIncidentTypeImage', options);

/**
 * Retrieve incident type image
 *
 * Retrieve the illustration image for an incident type
 */
export const getIncidentTypeImageOptions = (options: Options<GetIncidentTypeImageData>) => queryOptions<GetIncidentTypeImageResponse, GetIncidentTypeImageError, GetIncidentTypeImageResponse, ReturnType<typeof getIncidentTypeImageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentTypeImage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentTypeImageQueryKey(options)
});

export const getIncidentTypeOriginalImageQueryKey = (options: Options<GetIncidentTypeOriginalImageData>) => createQueryKey('getIncidentTypeOriginalImage', options);

/**
 * Retrieve original incident type image
 *
 * Retrieve the original incident type image from storage
 */
export const getIncidentTypeOriginalImageOptions = (options: Options<GetIncidentTypeOriginalImageData>) => queryOptions<GetIncidentTypeOriginalImageResponse, GetIncidentTypeOriginalImageError, GetIncidentTypeOriginalImageResponse, ReturnType<typeof getIncidentTypeOriginalImageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIncidentTypeOriginalImage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIncidentTypeOriginalImageQueryKey(options)
});
